import { StyleSheet } from "react-native";
import { windowHeight, windowWidth } from "../../services/utils";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 50,
    paddingHorizontal: 20,
    backgroundColor: "#fff",
    position: "relative",
    width: windowWidth,
    minHeight: windowHeight,
  },
  welcomeText: {
    fontSize: 60,
    fontWeight: "900",
    color: "#fff",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 10,
    paddingTop: 0,
    paddingRight: 0,
    fontFamily: "sans-serif",
    paddingBottom: 8,
    alignSelf: "center",
    textAlign: "left",
  },
  loginText: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 10,
  },
  input: {
    width: "100%",
    height: 50,
    backgroundColor: "rgba(0, 0, 0, .04)",
    color: "rgba(0, 0, 0, 1)",
    borderRadius: 6,
    marginBottom: 12,
    paddingBottom: 12,
    paddingTop: 12,
    paddingLeft: 16,
    paddingRight: 16,
    paddingHorizontal: 10,
    fontSize: 16,
  },
  fpText: {
    alignSelf: "flex-end",
    color: "#0a7cff",
    fontSize: 18,
    fontWeight: "600",
    marginTop: 10,
    textDecorationLine: "underline",
  },
  loginButton: {
    backgroundColor: "#0a7cff",
    paddingVertical: 12,
    borderRadius: 50,
    marginTop: 20,
    width: "30%",
  },
  loginButtonText: {
    fontSize: 20,
    fontWeight: "500",
    color: "#fafafa",
    alignSelf: "center",
  },
  loginWithBar: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 50,
  },
  iconButton: {
    backgroundColor: "#0a7cff",
    padding: 14,
    fontSize: 30,
    height: 50,
    width: 50,
    marginHorizontal: 10,
    borderRadius: 50,
  },
  signUpTextView: {
    marginTop: 40,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  signUpText: {
    color: "#808e9b",
    fontSize: 20,
    fontWeight: "500",
  },
});
