export const images = {
    user_1: require('../images/images/user1.png'),
    user_2: require('../images/images/user2.png'),
    user_3: require('../images/images/user3.png'),
    user_4: require('../images/images/user4.png'),
    user_5: require('../images/images/user5.png'),
    user_6: require('../images/images/user6.png'),
    footerBg: require('../images/images/footerbg.png'),
    checked: require('../images/images/checked.png'),
    un_checked: require('../images/images/Unchecked.png'),
    chat_inactive: require('../images/images/chat-inactive.png'),
    chat_active: require('../images/images/chat-active.png'),
    people_inactive: require('../images/images/people.png'),
    people: require('../images/images/people-active.png'),
    stories: require('../images/images/discover-active.png'),
    stories_inactive: require('../images/images/discover-inactive.png'),
    avatar: require('../images/images/avatar.png'),
    take_photo: require('../images/images/take-photo.png'),
    new_message: require('../images/images/new-message.png'),
    search: require('../images/images/search.png'),
    calls: require('../images/images/video.png'),
    calls_inactive: require('../images/images/video-call.png'),
    your_story: require('../images/images/your-story.png'),
};

